// src/components/AgentStatusDisplay.tsx
import React from 'react';
import { useStatusStore } from '@/stores/statusStore';

const AgentStatusDisplay: React.FC = () => {
  const latestStatus = useStatusStore((state) => state.latestStatus);

  if (!latestStatus) {
    return null; // Don't render anything if there's no status
  }

  return (
    <div style={styles.statusBar}>
      <span style={styles.icon}>⏳</span> {latestStatus}
    </div>
  );
};

// Basic inline styles for simplicity, consider moving to CSS/CSS-in-JS
const styles: { [key: string]: React.CSSProperties } = {
  statusBar: {
    backgroundColor: '#e0f2fe', /* Light blue background */
    color: '#0c4a6e', /* Dark blue text */
    padding: '5px 15px',
    fontSize: '0.85rem',
    textAlign: 'center',
    borderBottom: '1px solid #bae6fd',
    position: 'fixed',
    top: '60px', /* Adjust based on your header/layout */
    left: 0,
    width: '100%',
    zIndex: 50, /* Ensure visibility */
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.05)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  icon: {
    marginRight: '8px',
  },
};

export default AgentStatusDisplay;

// src/components/AgentStatusDisplay.vue
<template>
  <div v-if="statusMessage" class="agent-status-bar">
    <span class="status-icon">⏳</span> {{ statusMessage }}
  </div>
</template>

<script setup>
import { computed } from 'vue';
import { useStatusStore } from '@/stores/statusStore'; // Assuming a Pinia store

const statusStore = useStatusStore();
const statusMessage = computed(() => statusStore.latestStatus);

</script>

<style scoped>
.agent-status-bar {
  background-color: #e0f2fe; /* Light blue background */
  color: #0c4a6e; /* Dark blue text */
  padding: 5px 15px;
  font-size: 0.85rem;
  text-align: center;
  border-bottom: 1px solid #bae6fd;
  position: fixed; /* Or adjust based on layout - maybe relative? */
  top: 60px; /* Adjust based on header height */
  left: 0;
  width: 100%;
  z-index: 50; /* Ensure it's visible */
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
  display: flex;
  align-items: center;
  justify-content: center;
}

.status-icon {
  margin-right: 8px;
  /* Optional: Add animation */
  /* animation: spin 2s linear infinite; */
}

/* Optional animation for icon */
/*
@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
*/
</style>
